In [1]:
import sys
from pathlib import Path

project_root = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
sys.path.append(str(project_root / "src"))

import pandas as pd
from plastech.data_catalog import dataset_info, list_datasets, read_dataset

In [2]:
DATASET_NAME = "raw_inverse"

In [3]:
dataset_info(DATASET_NAME)

{'path': 'data/配合・物性一覧表(逆解析用)_Rev1.csv',
 'encoding': 'cp932',
 'description': '逆解析用の元データ'}

In [4]:
raw_inverse_df = read_dataset(DATASET_NAME)
raw_inverse_df.head()

,種別名称,ＫＦＲ,ＰＶＣ,ＰＶＣ.1,ＰＶＣ.2,ＰＶＣ.3,ＰＶＣ.4,ＰＶＣ.5,ＰＶＣ.6,ＰＶＣ.7,...,280010,290010,290010.1,290010.2,300010,300010.1,300010.2,110120.3,110120.4,110120.5
0,原料種類,Unnamed: 1_level_1,ＰＶＣ １３００,架橋ＰＶＣ １３００,架橋ＰＶＣ２２５１－,架橋ＰＶＣ ８００,Ｃ・ＰＶＣ－６５０,Ｃ・ＰＶＣ－６５０,Ｃ・ＰＶＣ－６５０,Ｃ・ＰＶＣ １０００,...,ｷｮｳｼ124ｺﾞｳ,IRM902100ﾟC*22h,IRM902100ﾟC*22h,IRM902100ﾟC*22h,Fuel C 23ﾟC*24h,Fuel C 23ﾟC*24h,Fuel C 23ﾟC*24h,100ﾟC*168h,100ﾟC*168h,100ﾟC*168h
1,原料名,4KFR014-3,3000HY(ｶｸｶﾞｲ),GR1300S,GR2500S,GR800T,HA15E,HA15F,HA15H,HA57K,...,加熱減量 ｷｮｳｼ124ｺﾞｳ,耐潤滑油 強さ変化率 IRM902100ﾟC*22h,耐潤滑油 伸び変化率 IRM902100ﾟC*22h,耐潤滑油 体積変化率 IRM902100ﾟC*22h,耐燃料油 強さ変化率 Fuel C 23ﾟC*24h,耐燃料油 伸び変化率 Fuel C 23ﾟC*24h,耐燃料油 体積変化率 Fuel C 23ﾟC*24h,熱老化 強さ変化率 100ﾟC*168h,熱老化 伸び変化率 100ﾟC*168h,熱老化 重量変化 100ﾟC*168h
2,CP0000000000001,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,CP0000000000002,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,CP0000000000003,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
raw_inverse_df.shape

(7847, 1208)

In [6]:
raw_inverse_df.columns

Index(['種別名称', 'ＫＦＲ', 'ＰＶＣ', 'ＰＶＣ.1', 'ＰＶＣ.2', 'ＰＶＣ.3', 'ＰＶＣ.4', 'ＰＶＣ.5',
       'ＰＶＣ.6', 'ＰＶＣ.7',
       ...
       '280010', '290010', '290010.1', '290010.2', '300010', '300010.1',
       '300010.2', '110120.3', '110120.4', '110120.5'],
      dtype='object', length=1208)

In [7]:
raw_inverse_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7847 entries, 0 to 7846
Columns: 1208 entries, 種別名称 to 110120.5
dtypes: object(1208)
memory usage: 72.3+ MB

In [8]:
raw_inverse_df.describe(include="all")

,種別名称,ＫＦＲ,ＰＶＣ,ＰＶＣ.1,ＰＶＣ.2,ＰＶＣ.3,ＰＶＣ.4,ＰＶＣ.5,ＰＶＣ.6,ＰＶＣ.7,...,280010,290010,290010.1,290010.2,300010,300010.1,300010.2,110120.3,110120.4,110120.5
count,7847,7847,7847,7847,7847,7847,7847,7847,7847,7847,...,7847,7847,7847,7847,7847,7847,7847,7847,7847,7847
unique,7847,3,4,9,6,15,4,5,8,5,...,6,19,16,13,18,14,19,17,13,17
top,原料種類,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
freq,1,7845,7844,7806,7820,7740,7839,7837,7813,7839,...,7841,7827,7828,7827,7827,7829,7827,7828,7830,7827