In [1]:
import sys
from pathlib import Path

project_root = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
sys.path.append(str(project_root / "src"))

import pandas as pd
from plastech.data_catalog import dataset_info, list_datasets, read_dataset

In [2]:
DATASET_NAME = "processed_main"

In [3]:
dataset_info(DATASET_NAME)

{'path': 'data/processed_data.csv',
 'encoding': 'utf-8-sig',
 'description': '主に分析で使う加工済みデータ'}

In [4]:
processed_main_df = read_dataset(DATASET_NAME)
processed_main_df.head()

,Unnamed: 0,KFR,PVC,PVC.1,PVC.2,PVC.3,PVC.4,PVC.5,PVC.6,PVC.7,...,S13010_130010,S14010_140010,S14010_140020,S15010_150030,S17010_170040,S18010_180020,S18010_180030,S21010_210010,S05010_050010_1,S05010_050010_2
0,NaN,0,C・PVC1000,C・PVC-650,C・PVC-650,C・PVC-650,EVAグラフト塩ビ,EVAグラフト塩ビ,EVAグラフト塩ビ,E・PVC1000,...,脆化温度,ビカット軟化温度,ビカット軟化温度,荷重たわみ温度,加熱変形率,体積抵抗率,体積抵抗率,酸素指数,熱安定性,熱安定性
1,NaN,4KFR014-3,HA57K,HA17H,HA15F,HA15E,TG110,TG120,TG130,TE1050,...,脆化温度_JISK6723_S13010_130010,ビカット軟化温度_10N_S14010_140010,ビカット軟化温度_50N_S14010_140020,荷重たわみ温度_1.82MPaEt12.7_S15010_150030,加熱変形率_120ﾟC*1kg*1h_S17010_170040,体積抵抗率_30ﾟC_S18010_180020,体積抵抗率_60ﾟC_S18010_180030,酸素指数_23ﾟCtype4_S21010_210010,熱安定性_180ﾟC_S05010_050010_1,熱安定性_180ﾟC_S05010_050010_2
2,CP0000000000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-34.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,183,0
3,CP0000000000002,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-38.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
4,CP0000000000003,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-49.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0

In [5]:
processed_main_df.shape

(5223, 569)

In [6]:
processed_main_df.columns

Index(['Unnamed: 0', 'KFR', 'PVC', 'PVC.1', 'PVC.2', 'PVC.3', 'PVC.4', 'PVC.5',
       'PVC.6', 'PVC.7',
       ...
       'S13010_130010', 'S14010_140010', 'S14010_140020', 'S15010_150030',
       'S17010_170040', 'S18010_180020', 'S18010_180030', 'S21010_210010',
       'S05010_050010_1', 'S05010_050010_2'],
      dtype='object', length=569)

In [7]:
processed_main_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5223 entries, 0 to 5222
Columns: 569 entries, Unnamed: 0 to S05010_050010_2
dtypes: object(569)
memory usage: 22.7+ MB

In [8]:
processed_main_df.describe(include="all")

,Unnamed: 0,KFR,PVC,PVC.1,PVC.2,PVC.3,PVC.4,PVC.5,PVC.6,PVC.7,...,S13010_130010,S14010_140010,S14010_140020,S15010_150030,S17010_170040,S18010_180020,S18010_180030,S21010_210010,S05010_050010_1,S05010_050010_2
count,5221,5223,5223,5223,5223,5223,5223,5223,5223,5223,...,5223,5223,5223,5223,5223,5223,5223,5223,5223,5223
unique,5221,3,5,6,6,4,6,7,7,6,...,56,217,197,30,183,498,494,66,170,56
top,CP0000000000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
freq,1,5221,5215,5207,5212,5218,5211,5207,5214,5206,...,1829,4569,4822,5187,4106,4329,4401,4954,1451,5058